name: admin
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  #common
  cupertino_icons: ^1.0.8
  get: 4.6.6
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.5
  flutter_svg: ^2.0.10+1
  nb_utils: ^7.0.2
  easy_search_bar: ^2.5.0
  uuid: ^4.4.0
  intl: ^0.17.0
  image_picker: ^1.1.1
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  html_editor_enhanced: ^2.6.0
  html: ^0.15.4
  provider: ^6.1.2
  aligned_dialog: ^0.0.7
  geoflutterfire2: ^2.3.15
  flex_color_picker: ^3.4.0
  url_strategy: ^0.2.0
  syncfusion_flutter_datagrid: ^23.2.7
  syncfusion_flutter_charts: ^23.2.7
  flutter_easyloading: ^3.0.5
  file_picker: ^8.0.3
  path_provider: ^2.1.3
  url_launcher: ^6.2.6
  flutter_custom_text_input_formatter: ^0.0.4
  location: ^6.0.2
  map_launcher: ^3.3.0
  timelines_plus: ^1.0.2
  syncfusion_flutter_datepicker:


  #Firebase
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  firebase_storage: ^11.7.7
  flutter_local_notifications: ^17.1.2


dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/image/
    - assets/icons/
    - assets/animation/

  fonts:
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf

    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf

    - family: Inter-Light
      fonts:
        - asset: assets/fonts/Inter-Light.ttf

    - family: Inter-Thin
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf

    - family: Inter-ExtraBold
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf

    - family: Recoleta-SemiBold
      fonts:
        - asset: assets/fonts/Recoleta-SemiBold.ttf
