// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsO3KRv-cWcpZbAif6PRohlinm72m5BQI',
    appId: '1:107316073750:web:d6a05c01ce58d87008ac37',
    messagingSenderId: '107316073750',
    projectId: 'metrotaxi-782a6',
    authDomain: 'metrotaxi-782a6.firebaseapp.com',
    storageBucket: 'metrotaxi-782a6.appspot.com',
    measurementId: 'G-NHS7T68J8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIXlDAva_RnlC5kiTPfh99o_vOJkWbnEM',
    appId: '1:107316073750:android:a9a33daa0e79e76008ac37',
    messagingSenderId: '107316073750',
    projectId: 'metrotaxi-782a6',
    storageBucket: 'metrotaxi-782a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvMCKDNnORaG3lfyhF0l04KI3MmyAqLHg',
    appId: '1:107316073750:ios:e8f6a2fcb3814beb08ac37',
    messagingSenderId: '107316073750',
    projectId: 'metrotaxi-782a6',
    storageBucket: 'metrotaxi-782a6.appspot.com',
    iosBundleId: 'com.mytaxi.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvMCKDNnORaG3lfyhF0l04KI3MmyAqLHg',
    appId: '1:107316073750:ios:5acaf204cfdfe87108ac37',
    messagingSenderId: '107316073750',
    projectId: 'metrotaxi-782a6',
    storageBucket: 'metrotaxi-782a6.appspot.com',
    iosBundleId: 'com.metroberry.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsO3KRv-cWcpZbAif6PRohlinm72m5BQI',
    appId: '1:107316073750:web:0c8c18585cb2029808ac37',
    messagingSenderId: '107316073750',
    projectId: 'metrotaxi-782a6',
    authDomain: 'metrotaxi-782a6.firebaseapp.com',
    storageBucket: 'metrotaxi-782a6.appspot.com',
    measurementId: 'G-0QYGQVPCYZ',
  );

}