name: customer
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  sign_in_with_apple: ^6.1.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  flutterflow_paginate_firestore: ^1.0.3+1
  firebase_storage: ^11.7.7
  google_maps_place_picker_mb: ^3.1.2

  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.1.2
  auto_size_text_field: ^2.2.3

  get: 4.6.6
  provider: ^6.1.2

  country_code_picker: ^3.0.0
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
#  flutter_screenutil: ^5.9.0

  otp_text_field: ^1.1.3

  crypto: ^3.0.3
  intl: ^0.19.0

  timelines_plus: ^1.0.2
#  google_places_flutter: ^2.0.8
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.6.1
  location: ^6.0.2
  map_launcher: ^3.3.0
  geolocator: ^10.0.1
  geocoding: ^3.0.0
  geoflutterfire2: ^2.3.15
  googleapis_auth: ^1.6.0
  dio: ^5.4.3+1
  rxdart: ^0.27.7
  uuid: ^4.4.0

  http: ^1.2.1
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  flutter_widget_from_html: ^0.15.0
  flutter_rating_bar: ^4.0.1
  lottie: ^3.1.2

  #payment_dependencies
  flutter_stripe: ^10.1.1
  flutter_paypal_native: ^2.1.0
  razorpay_flutter: ^1.3.7
  flutterwave_standard: ^1.0.8
  mercadopago_sdk: ^1.3.0

  url_launcher: ^6.3.0
  package_info_plus: ^4.1.0


dependency_overrides:
  http: ^1.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/animation/
