name: Metroberry Mobile Applications

on:
  push:
    branches: ["serverChanges"]
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print working directory
        run: pwd
      - name: List files
        run: ls -la
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
